environment:          production
log.error_file:       site.log
server.socket_host:   0.0.0.0
server.socket_port:   8088
engine.autoreload.on: True
log.screen:           True

tools.lg_authority.on: True 

tools.lg_authority.site_registration:   email
tools.lg_authority.site_storage:        sqlite3 
tools.lg_authority.site_storage_conf:
  file: auth.db
tools.lg_authority.site_template_dir:   app/data/pages/auth/
tools.lg_authority.site_email:
  smtpserver:   erazor-zone.de
  smtpport:     25
  smtpssl:      False
  smtpuser:     __unset__
  smtppass:     __unset__
  default:      Site <test@example.com>'
